<?php 


return [
    #10个配置
    [
        'csnickname'=>'aa',
        'wechatid'=>'aawechat'
    ],
    [
        'csnickname'=>'bb',
        'wechatid'=>'aawechat_bb'
    ],
    [
        'csnickname'=>'cc',
        'wechatid'=>'aawechat_cc'
    ],
    [
        'csnickname'=>'dd',
        'wechatid'=>'aawechat_dd'
    ],
    [
        'csnickname'=>'ee',
        'wechatid'=>'aawechat_ee'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    #10个配置

    [
        'csnickname'=>'aa',
        'wechatid'=>'aawechat'
    ],
    [
        'csnickname'=>'bb',
        'wechatid'=>'aawechat_bb'
    ],
    [
        'csnickname'=>'cc',
        'wechatid'=>'aawechat_cc'
    ],
    [
        'csnickname'=>'dd',
        'wechatid'=>'aawechat_dd'
    ],
    [
        'csnickname'=>'ee',
        'wechatid'=>'aawechat_ee'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],
    [
        'csnickname'=>'ff',
        'wechatid'=>'aawechat_ff'
    ],


];
